# Generated by Django 2.2.2 on 2021-07-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CMND', models.CharField(max_length=50)),
                ('ten', models.CharField(max_length=50)),
                ('ngay_sinh', models.DateField()),
                ('benh_nen', models.CharField(max_length=50)),
                ('tien_su_benh', models.CharField(max_length=100)),
                ('di_ung', models.CharField(max_length=50)),
                ('loai_vac_xin', models.CharField(max_length=50)),
                ('ngay_tiem', models.DateField()),
                ('so_lan_tiem', models.IntegerField()),
            ],
        ),
    ]
