# Generated by Django 3.2.5 on 2021-07-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hop_dong', models.CharField(max_length=50)),
                ('ngay_ky', models.DateField()),
                ('ten_khach_hang', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('ngay_hieu_luc', models.DateField()),
                ('ngay_ngay_het_han', models.DateField()),
                ('thoi_han', models.CharField(max_length=50)),
                ('gia_thue', models.IntegerField()),
                ('tien_coc', models.IntegerField()),
            ],
        ),
    ]
