# Generated by Django 3.1.1 on 2022-05-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('debt', models.FloatField()),
                ('due_date', models.DateField()),
                ('is_overdued', models.BooleanField()),
                ('is_reminded', models.BooleanField()),
            ],
        ),
    ]
