# Generated by Django 3.1.1 on 2022-05-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_reminder', '0002_auto_20220512_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_overdued',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('overdue', 'overdue')], default='normal', max_length=50),
        ),
    ]
