# Generated by Django 4.1.7 on 2023-04-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt_reminder', '0003_auto_20220512_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('normal', 'Normal'), ('overdue', 'Overdue')], default='normal', max_length=50),
        ),
    ]
