# Generated by Django 4.1.7 on 2023-04-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=255)),
                ('serial', models.CharField(max_length=255)),
                ('po_contact_no', models.CharField(max_length=255)),
                ('currency_code', models.CharField(max_length=255)),
                ('vat_code', models.CharField(max_length=255)),
                ('pretax_amt', models.FloatField(max_length=255)),
                ('vat_amt', models.FloatField(max_length=255)),
                ('total_amt', models.FloatField(max_length=255)),
            ],
        ),
    ]
