# Generated by Django 2.2.2 on 2021-07-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('unit_price', models.FloatField()),
                ('total_amount', models.FloatField()),
            ],
        ),
    ]
